[build]
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Przekierowanie dla obrazów statycznych
[[redirects]]
  from = "/uploads/*"
  to = "/uploads/:splat"
  status = 200
